---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    name: "Unit Tests (${{ matrix.stack }})"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        stack:
          - scalingo-20
          - scalingo-22
    container:
      image: "scalingo/${{ matrix.stack }}:latest"
      env:
        STACK: "${{ matrix.stack }}"
    steps:
      - name: ðŸ›Ž  Checkout
        uses: actions/checkout@v4

      - name: ðŸ”Ž Run tests
        run: |
          test/run
...
